// Authored practice advice, not generated doorway pages. These pages are written in
// English about learning each language; they are not translations (no false hreflang).
export type LanguageGuide = {
  slug: string; name: string; code: string; flag: string;
  focus: string; listening: string; speaking: string; example: string; meaning: string;
  exercise: string; question: string; answer: string;
};
export const LANGUAGE_GUIDES: readonly LanguageGuide[] = [
  { slug: 'spanish', name: 'Spanish', code: 'es-ES', flag: '🇪🇸',
    focus: 'Hear word boundaries in connected speech and build a steady speaking rhythm.',
    listening: 'Start with a short exchange rather than isolated vocabulary. Listen for where one word runs into the next, then check the transcript after your first attempt.',
    speaking: 'Repeat the whole phrase before working on individual sounds. Pay attention to clear vowels and the stressed syllable; use the same speaker as your model for each round.',
    example: '¿Puedes hablar un poco más despacio?', meaning: 'Can you speak a little more slowly?',
    exercise: 'Practise the request as one sentence. Then replace “más despacio” with “más alto” to ask someone to speak louder. Listen for how the stress changes.',
    question: 'Should I practise Spanish from Spain or Latin America?', answer: 'Choose audio that matches the people you expect to speak with. Bantera offers Spanish language options for different regions. Check each lesson’s language label and recording, because pronunciation and vocabulary vary by speaker and region.' },
  { slug: 'french', name: 'French', code: 'fr-FR', flag: '🇫🇷',
    focus: 'Recognise connected phrases, then repeat their rhythm and intonation.',
    listening: 'Spelling alone can make French audio hard to follow. Listen for a whole phrase first, reveal the transcript, then replay to notice which sounds connect across words.',
    speaking: 'Copy the speaker’s phrase grouping. Start slowly, then return to normal speed without forcing every written letter into your recording.',
    example: 'Vous pouvez répéter, s’il vous plaît ?', meaning: 'Could you repeat that, please?',
    exercise: 'Repeat the polite request, pause, and say it again without reading. Keep “s’il vous plaît” together as a familiar spoken chunk.',
    question: 'How can I follow French when it sounds faster than the transcript?', answer: 'Use short audio cues and listen twice before reading. Then compare the words on the page with the sounds you actually hear. Repeat the connected phrase, gradually bringing playback back to normal speed.' },
  { slug: 'mandarin', name: 'Mandarin Chinese', code: 'zh-CN', flag: '🇨🇳',
    focus: 'Practise tones in everyday phrases alongside listening comprehension.',
    listening: 'Listen to the same short sentence several times. Follow the rise and fall of the speaker’s voice, then use the transcript to check which words you heard.',
    speaking: 'Copy the full phrase, including its tone pattern and pauses. Record and replay your voice beside the original; a matching transcription alone does not prove that your tones match.',
    example: '请再说一遍。', meaning: 'Please say that again.',
    exercise: 'Listen for the rhythm of “再说一遍” as a phrase. Repeat the complete request from memory, then compare your recording with the original.',
    question: 'Does a correct Mandarin transcription mean my tones are correct?', answer: 'No. Speech recognition may infer a word from context. Use the transcription as one clue, then listen to both recordings and compare the tone movement. Bantera does not claim a phoneme or tone accuracy score.' },
  { slug: 'japanese', name: 'Japanese', code: 'ja-JP', flag: '🇯🇵',
    focus: 'Hear phrase endings and practise the timing of short spoken exchanges.',
    listening: 'Listen through to the end of a sentence before deciding what it means. Notice particles and polite endings, then check the transcript and replay the same cue.',
    speaking: 'Give long vowels and doubled consonants time in your repetition. Copy the speaker’s timing rather than fitting the sentence into the rhythm of your first language.',
    example: 'もう一度お願いします。', meaning: 'One more time, please.',
    exercise: 'Listen, repeat, then ask the same request without looking. Pay attention to the length of “もう” and the flow into “一度”.',
    question: 'Can I practise Japanese speaking before reading every character?', answer: 'You can begin by listening and repeating short cues. Reveal the transcript as support when you need it. Choose audio you can mostly understand, and treat reading study as a separate part of your learning routine.' },
  { slug: 'korean', name: 'Korean', code: 'ko-KR', flag: '🇰🇷',
    focus: 'Follow connected sounds and practise useful polite phrases aloud.',
    listening: 'Notice how syllables sound together in a sentence rather than expecting each written block to sound isolated. Replay a short cue and check its ending in the transcript.',
    speaking: 'Repeat the entire polite phrase with the same pauses as the speaker. Record it, listen again, and choose one sound or transition to practise on the next attempt.',
    example: '다시 말해 주세요.', meaning: 'Please say that again.',
    exercise: 'Repeat the request with a relaxed pause after it. Then hide the text and imagine asking a conversation partner to repeat a sentence.',
    question: 'What should I focus on in a short Korean listening session?', answer: 'Choose one short exchange and listen for the words you know and the sentence ending. Replay the parts you missed, read the transcript, and finish by saying the whole phrase without the text.' },
  { slug: 'german', name: 'German', code: 'de-DE', flag: '🇩🇪',
    focus: 'Follow complete sentences and practise their stress and phrase endings.',
    listening: 'Listen to the full cue, including the final words. Use the transcript to spot where the verb and key information occur, then replay without reading.',
    speaking: 'Break a longer sentence into meaningful chunks before repeating it as a whole. Keep the stressed words clear and compare consonant endings with the recording.',
    example: 'Können Sie das bitte wiederholen?', meaning: 'Could you repeat that, please?',
    exercise: 'Repeat the polite request, then try “Kannst du das bitte wiederholen?” for an informal conversation. Notice the difference in the opening words.',
    question: 'How do I move from understanding German words to following sentences?', answer: 'Practise complete short cues instead of replaying only isolated words. First listen for the overall message, then read to resolve what you missed. Repeat the full sentence so its structure becomes familiar in speech.' },
  { slug: 'italian', name: 'Italian', code: 'it-IT', flag: '🇮🇹',
    focus: 'Build clear vowel sounds and practise the rhythm of everyday Italian.',
    listening: 'Choose a short conversation and listen for stressed syllables. Check the transcript after listening, then notice how the words join into a phrase.',
    speaking: 'Copy the vowel length and consonant timing you hear. Repeating a whole cue helps you practise the musical shape of the sentence as well as its individual words.',
    example: 'Puoi ripetere, per favore?', meaning: 'Can you repeat that, please?',
    exercise: 'Repeat the request naturally, then pause and say it again from memory. Keep “per favore” as one familiar expression.',
    question: 'How can I practise Italian speaking on my own?', answer: 'Play a short cue, repeat it aloud, and record yourself. Compare the two recordings, choose one difference to work on, and repeat. A few focused cues are enough for a short solo practice session.' },
  { slug: 'portuguese', name: 'Portuguese', code: 'pt-BR', flag: '🇧🇷',
    focus: 'Get used to spoken Portuguese and practise phrases with a consistent accent model.',
    listening: 'Choose a Brazilian or European Portuguese recording that fits your goal. Listen for how unstressed syllables sound in that recording before checking the written words.',
    speaking: 'Copy one speaker at a time, paying attention to vowel sounds and the flow between words. Keep the same cue for several attempts so you can compare changes.',
    example: 'Pode repetir, por favor?', meaning: 'Could you repeat that, please?',
    exercise: 'Say the request after hearing it. Then record it without the transcript and compare the rhythm of “repetir” and “por favor” with the original.',
    question: 'Does Bantera have Brazilian and European Portuguese options?', answer: 'The language catalogue includes Portuguese for Brazil and Portugal. Public lesson availability varies; use the language label and the recording to choose a suitable model for your practice.' },
  { slug: 'arabic', name: 'Arabic', code: 'ar-SA', flag: '🇸🇦',
    focus: 'Practise understanding and repeating short Arabic phrases with a clear learning goal.',
    listening: 'Check whether a recording matches the variety of Arabic you want to understand. Listen for the overall message, then repeat short sections with the transcript as support.',
    speaking: 'Use the same recording for several attempts. Compare vowel length and the consonants you find difficult, working on one part of the phrase at a time.',
    example: 'هل يمكنك أن تتكلم ببطء؟', meaning: 'Can you speak slowly?',
    exercise: 'This is a Modern Standard Arabic example. Listen to a suitable recording before repeating; for everyday dialect practice, choose phrases used by speakers of that dialect.',
    question: 'Are all Arabic lessons interchangeable across dialects?', answer: 'No. Arabic varies across regions, and Modern Standard Arabic differs from everyday dialects. Regional language options alone do not guarantee a particular dialect in each lesson. Check the actual content and choose audio that fits your goal.' },
  { slug: 'english', name: 'English', code: 'en-US', flag: '🇺🇸',
    focus: 'Hear connected speech and practise sentence stress in everyday conversations.',
    listening: 'Listen once without text for the main idea. On the second pass, focus on words that seem to disappear or join together, then check the transcript.',
    speaking: 'Repeat a whole phrase with its stressed words and pauses. Use a recording in the accent you want to understand; compare your voice with the original after each attempt.',
    example: 'Could you say that a little more slowly?', meaning: 'A polite request to slow down.',
    exercise: 'Stress “little” and “slowly” naturally rather than giving every word equal weight. Then make your own request using “Could you explain that again?”',
    question: 'Can I practise different English accents?', answer: 'Bantera’s language catalogue includes regional English options such as US, UK, Australian and New Zealand English. Public lesson availability varies, so check the lesson label and listen to the speaker before choosing your practice material.' },
];
export function languageGuide(slug: string) { return LANGUAGE_GUIDES.find(l => l.slug === slug); }
