// Add supplied files to public/presentation and set their URLs here.
// Keep null until the actual media is available; no broken media requests.
export const media: Record<'demo' | 'deployment' | 'backup' | 'closing', string | null> = {
  demo: '/presentation/bantera-demo-hevc.mp4',
  deployment: '/presentation/openclaw-deployment.png',
  backup: '/presentation/openclaw-daily-backup.png',
  closing: null,
};

export const demoVideo = {
  fallback: '/presentation/bantera-demo.mp4',
  poster: '/presentation/bantera-demo-poster.jpg',
};

// Original Traditional Chinese lyrics supplied by the user.
// Meaning-based English adaptation inspired by the colours passage, not an official lyric translation.
// Verified against https://www.shazam.com/song/1792345291/e58589e8bc9de6adb2e69c88-live
// The English reflection on the slide is the presenter's own thought, not a lyric translation.
export const closingQuote = {
  chineseLyric: '繽紛色彩閃出的美麗\n是因它沒有 分開每種色彩',
  english: 'The world is more beautiful when all its colours come together.',
  translationNote: 'English inspired by the lyrics of Glorious Years · 光輝歲月',
  attribution: '黃家駒 · Wong Ka Kui',
  artistDescription: 'A great Hong Kong singer and songwriter · Beyond',
  source: 'https://www.youtube.com/watch?v=PrGsAMbgUh4',
};

export const slides = [
  { id: 'hello', title: 'A conversation worth building for', section: 'Hello', notes: 'Introduce yourself and Bantera. This is the story of why you wanted to build it, the choices you made, and how the pieces work together. About 20 minutes, with room for conversation.' },
  { id: 'google-maps', title: 'How did you find this class?', section: 'A small misunderstanding', notes: 'Describe the free English class at church and your English level then. Ask the question, pause, then press Next or Space to reveal your Google Maps answer. Explain that the organiser wanted your opinion of the class. The humour is in the misunderstanding.' },
  { id: 'why', title: 'More words. Still a difficult conversation.', section: 'Why I built it', notes: 'You kept learning vocabulary and reading. AI could help with written English, but you still wanted to understand and respond when meeting people face to face. Friends wanted practice too. AI also made it possible to extend the idea to other languages. Avoid making blanket claims about translation products.' },
  { id: 'accents', title: 'Even in my own language', section: 'The garage story', notes: 'First explain that you used Bantera to prepare an English dialogue for a car repair. At the garage, the mechanic spoke Chinese, but his accent was unfamiliar. You understood perhaps 70% and asked him to repeat himself. This reinforced why accent familiarity matters. Do not imitate or make fun of his accent.' },
  { id: 'sweet-as', title: 'Sweet as', section: 'Language in everyday life', notes: 'Last year you met a Kiwi and asked: “If you could teach me just one Kiwi slang expression, what would it be?” She thought for a moment and said “sweet as”. Recently you saw this sign at The Warehouse, remembered her, and sent her the photo saying you remembered learning it from her. She replied with a thumbs-up emoji and the laughing-with-tears emoji. Keep this warm and short. The current backend favours everyday regional language and explicitly discourages heavy slang. Do not promise a dedicated slang feature or that this exact phrase will appear in generated audio.' },
  { id: 'demo', title: 'A little practice before real life', section: 'Bantera in action', notes: 'Play the supplied 10.5-second recording of dialogue playback. Let the audience hear the sample without talking over it. Explain how listening and the highlighted words help you practise. Review accent quality in the recording before the talk.' },
  { id: 'language-accents', title: 'A language, and the accents within it', section: 'Choosing how to practise', notes: 'About 45 seconds. Return briefly to the garage story: knowing a language and being familiar with an accent are different things. Show the learning-language selector and the nine regional English options visible here, including New Zealand. Bantera also supports learning other languages. This screenshot shows the English options, not the full language list.' },
  { id: 'ai-scenarios', title: 'English I’m about to use', section: 'Creating a conversation', notes: 'About one minute. Explain that your English improves when you learn for a real situation. Before taking your car to the garage, you generate a car-repair dialogue and practise the vocabulary and expressions you expect to need. You do this before other everyday activities too. Describe it as learning through real situations, or learning as you use it. This is what works best for you, rather than a claim about the best method for everyone. The screenshot has Coffee shop selected and shows 15 preset scenarios plus Custom. Explain that you would use Custom for the garage example. The screen also offers a random scenario and durations from one to four minutes.' },
  { id: 'voice-exchange', title: 'We can help each other', section: 'Practising with people', notes: 'About one minute. Explain a possible exchange: you are a native Chinese speaker learning English, and another person is a native English speaker learning Chinese. You can help each other through voice messages. Outgoing messages are voice only, deliberately keeping speaking and listening at the centre. Transcription and translation provide support if a message is difficult to understand. The supplied screenshot shows voice messages, Transcribe buttons and Hold to record audio. Translation is a feature described by you, not shown expanded in this screenshot. Do not imply the named person in the screenshot has the language background of the hypothetical partner. Transition: those are the experiences I wanted to build, so here is how the technology works.' },
  { id: 'pipeline', title: 'Inside the AI pipeline', section: 'Inside the AI pipeline', notes: 'Use the supplied generation-progress screenshot to connect the app experience to the technology. Writing dialogue and generating audio are complete in this capture, while alignment is still in progress. Explain that choosing the situation comes before these stages, and listening, repeating, recording and comparing come afterwards. Verified in the backend: Gemini writes the dialogue and generates the speech, then timing alignment makes sentence practice possible. Rev.ai alignment has fallback paths; exact fallback differs by API version. The server stores audio and transcript data and sends progress updates. Keep the explanation about what each stage contributes.' },
  { id: 'codebases', title: 'Three codebases. One experience.', section: 'How I built it', notes: 'These are three separate repositories: Flutter for the mobile app, .NET for the backend, Next.js for the website. The website includes the homepage, shared practice pages, and administration. Explain one reason for your own choices, without inventing a rationale. PostgreSQL holds application data; audio objects use Cloudflare R2.' },
  { id: 'deployment', title: 'Running Bantera with OpenClaw', section: 'Running Bantera', notes: 'Describe using OpenClaw to manage Bantera on your Ubuntu server. This screenshot shows a request to deploy a new website version and the bot reporting success, the commit, HTTP 200 health checks, and running website and cloudflared containers. Walk through the request and the report. This is a historical website deployment example, not a live check of the server or evidence of a database backup. The slide focuses on the relevant exchange and leaves unrelated chats outside the visible crop.' },
  { id: 'backup', title: 'A backup, every day at 5 a.m.', section: 'Beyond the first deployment', notes: 'Explain that you configured an OpenClaw cron job to back up the Bantera database every day at 5 a.m. The file is sent directly to your chat and is available to download when you need it. The screenshot shows dated SQL ZIP attachments of about 1.8 MB delivered at 5 a.m. on 16 and 17 September. Emphasise that database backups are an important part of running the app. These attachments demonstrate delivery, not a tested database restore. The two image excerpts focus on the backup deliveries; the unrelated OpenClaw upgrade messages are outside the visible crops.' },
  { id: 'try', title: 'What would you practise?', section: 'Your turn', notes: 'Invite one or two examples from the audience. Share the site for people who want to try Bantera. Take technical questions here so the final reflection can remain the last slide.' },
  { id: 'colours', title: 'Every accent adds colour.', section: 'Why it matters', notes: 'Introduce Wong Ka Kui, a great Hong Kong singer and songwriter from Beyond, and the colours passage from Glorious Years. The English line is inspired by the lyrics: the world is more beautiful when all its colours come together. It is a meaning-based adaptation, not an official or line-by-line translation. The song concerns racial equality; the connection to accents is your own reflection. Source: https://www.youtube.com/watch?v=PrGsAMbgUh4. Then move clearly into your own reflection: different accents make the world richer, and you want to understand people from all over the world and make friends with them. The English slide copy is your reflection, not a translation or a claim that the song is about accents. You have an accent too. End warmly: you would love to meet people from all over the world and make new friends.' },
] as const;
